//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbTools.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbTools.Core.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear screen.
        /// </summary>
        internal static string @__cli_cmd__cls {
            get {
                return ResourceManager.GetString("__cli_cmd__cls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate an fake DB structure
        ///-f  DB schema file
        ///-o  Output file
        ///-v  Verbose.
        /// </summary>
        internal static string @__cli_cmd__genfakestruct {
            get {
                return ResourceManager.GetString("__cli_cmd__genfakestruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print help (documentation).
        /// </summary>
        internal static string @__cli_cmd__help {
            get {
                return ResourceManager.GetString("__cli_cmd__help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize a new DB schema file
        ///-c  Connection string
        ///-n  Schema name
        ///-o  Output file
        ///-v  Verbose.
        /// </summary>
        internal static string @__cli_cmd__init {
            get {
                return ResourceManager.GetString("__cli_cmd__init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit program.
        /// </summary>
        internal static string @__cli_cmd__quit {
            get {
                return ResourceManager.GetString("__cli_cmd__quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not recognized as command.
        /// </summary>
        internal static string @__cli_error__0__is_not_recognized_as_command {
            get {
                return ResourceManager.GetString("__cli_error__0__is_not_recognized_as_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undocumented command.
        /// </summary>
        internal static string @__cli_undocumented_command {
            get {
                return ResourceManager.GetString("__cli_undocumented_command", resourceCulture);
            }
        }
    }
}
